/**
 * Khmer-first copy shared by the Admin portal, Telegram Mini App, and API.
 * Keep route names, enum values, and API error codes out of this file: those
 * are programmatic identifiers, not worker-facing copy.
 */
export const km = {
  app: {
    title: 'ប្រព័ន្ធវត្តមានការដ្ឋាន',
    description: 'ប្រព័ន្ធគ្រប់គ្រងបុគ្គលិក និងវត្តមានការដ្ឋាន',
    loading: 'កំពុងផ្ទៀងផ្ទាត់សិទ្ធិ…',
    connectingTelegram: 'កំពុងភ្ជាប់ Telegram…',
    loadingAttendance: 'កំពុងផ្ទុកវត្តមានថ្ងៃនេះ…',
    startupSlow: 'ការតភ្ជាប់ចំណាយពេលយូរជាងធម្មតា…',
    sessionExpired: 'សម័យចូលប្រើបានផុតកំណត់។ សូមចូលប្រើម្តងទៀត។',
  },
  auth: {
    portalTitle: 'ប្រព័ន្ធគ្រប់គ្រងវត្តមាន',
    portalSubtitle: 'ចូលប្រើដោយគណនីពិតរបស់អង្គភាពអ្នក។',
    signIn: 'ចូលប្រើ',
    signOut: 'ចាកចេញ',
    confirmSignOutTitle: 'ចាកចេញពីប្រព័ន្ធ?',
    confirmSignOutDescription: 'អ្នកនឹងត្រូវចូលប្រើម្ដងទៀត ដើម្បីបន្តគ្រប់គ្រងអង្គភាពនេះ។',
    createOrganization: 'បង្កើតអង្គភាពថ្មី',
    organizationName: 'ឈ្មោះអង្គភាព',
    organizationSlug: 'លេខសម្គាល់អង្គភាព',
    email: 'អ៊ីមែលម្ចាស់គណនី',
    password: 'ពាក្យសម្ងាត់',
    passwordHint: 'យ៉ាងតិច ១២ តួអក្សរ',
    signingIn: 'កំពុងចូលប្រើ…',
    creating: 'កំពុងបង្កើត…',
    noAccount: 'មិនទាន់មានអង្គភាព?',
    haveAccount: 'មានអង្គភាពរួចហើយ?',
    registrationIntro: 'បង្កើតអង្គភាព និងគណនីម្ចាស់ដំបូង។ ទិន្នន័យគំរូនឹងមិនត្រូវបានបង្កើតទេ។',
  },
  actions: {
    cancel: 'បោះបង់',
    processing: 'កំពុងដំណើរការ…',
    saving: 'កំពុងរក្សាទុក…',
    saved: 'បានរក្សាទុក និងធ្វើបច្ចុប្បន្នភាពរួចរាល់។',
    saveFailed: 'មិនអាចរក្សាទុកបានទេ។ សូមពិនិត្យព័ត៌មាន ហើយសាកល្បងម្ដងទៀត។',
    confirmChanges: 'បញ្ជាក់ការកែប្រែ',
    confirmSettingsTitle: 'រក្សាទុកការកំណត់ថ្មី?',
    confirmSettingsDescription: 'ឈ្មោះ ពណ៌ និងភាសារបស់អង្គភាពនឹងត្រូវបានធ្វើបច្ចុប្បន្នភាពសម្រាប់ប្រព័ន្ធ។',
    noChanges: 'មិនមានការកែប្រែដែលត្រូវរក្សាទុកទេ។',
    unsavedChanges: 'មានការកែប្រែមិនទាន់រក្សាទុក។',
    uploading: 'កំពុងផ្ទុកឡូហ្គោ…',
    uploaded: 'បានផ្ទុក និងរក្សាទុកឡូហ្គោរួចរាល់។',
    confirmAccessTitle: 'រក្សាទុកសិទ្ធិចូលប្រើ?',
    confirmAccessDescription: 'អ្នកប្រើប្រាស់នេះនឹងអាចចូលប្រើតែគម្រោង និងការដ្ឋានដែលបានជ្រើស។',
    accessSaved: 'បានរក្សាទុកសិទ្ធិចូលប្រើរួចរាល់។',
    retry: 'សាកល្បងម្ដងទៀត',
    confirmDestinationTitle: 'ប្តូរទិសដៅសារ Telegram?',
    confirmDestinationDescription: 'ការជូនដំណឹងថ្មីនឹងត្រូវផ្ញើទៅទិសដៅដែលអ្នកបានជ្រើស។',
    destinationSaved: 'បានធ្វើបច្ចុប្បន្នភាពទិសដៅ Telegram រួចរាល់។',
    confirmArchiveTitle: 'ដកហូតអតិថិជននេះ?',
    confirmArchiveDescription: 'អតិថិជននេះនឹងលែងប្រើបានសម្រាប់ការចុះជួបថ្មី ប៉ុន្តែប្រវត្តិចាស់នៅតែរក្សាទុក។',
    archived: 'បានដកហូត និងធ្វើបច្ចុប្បន្នភាពបញ្ជីរួចរាល់។',
    correctionSubmitted: 'បានបញ្ជូនសំណើកែតម្រូវរួចរាល់។',
    correctionResolved: 'បានរក្សាទុកការសម្រេចរួចរាល់។',
    confirmRemovalTitle: 'បញ្ជាក់ការដកចេញ?',
    confirmRemovalDescription: 'សកម្មភាពនេះនឹងផ្លាស់ប្តូរទិន្នន័យដែលកំពុងប្រើ។ ប្រវត្តិដែលត្រូវរក្សាទុកនឹងមិនត្រូវបានលុបស្ងាត់ទេ។',
    remove: 'ដកចេញ',
    removed: 'បានដកចេញ និងធ្វើបច្ចុប្បន្នភាពទិន្នន័យរួចរាល់។',
    healthRefreshed: 'បានពិនិត្យ និងធ្វើបច្ចុប្បន្នភាពស្ថានភាព Telegram រួចរាល់។',
    exporting: 'កំពុងរៀបចំឯកសារ…',
    exported: 'បាននាំចេញឯកសាររួចរាល់។',
  },
  nav: {
    operations: 'ប្រតិបត្តិការថ្ងៃនេះ',
    workers: 'បញ្ជីបុគ្គលិក',
    sites: 'ការដ្ឋាន និងវេនការ',
    assignments: 'ការចាត់តាំងវេនការ',
    telegramReporting: 'ការជូនដំណឹង Telegram',
    attendance: 'វត្តមាន',
    sales: 'ក្រុមលក់',
    reports: 'របាយការណ៍',
    security: 'សុវត្ថិភាព',
    settings: 'ការកំណត់',
    management: 'ការគ្រប់គ្រងបុគ្គលិក',
  },
  admin: {
    attendanceTitle: 'ពិនិត្យវត្តមាន និងករណីលើកលែង',
    attendanceSubtitle: 'ពិនិត្យភស្តុតាង ទីតាំង និងកែតម្រូវកំណត់ត្រាដោយមានប្រវត្តិច្បាស់លាស់។',
    exceptionsOnly: 'ករណីត្រូវពិនិត្យ',
    allAttendance: 'វត្តមានទាំងអស់',
    evidence: 'ភស្តុតាង',
    details: 'មើលលម្អិត',
    correction: 'ស្នើកែតម្រូវ',
    reason: 'មូលហេតុ',
    correctedProject: 'គម្រោងដែលត្រឹមត្រូវ',
    submitCorrection: 'បញ្ជូនសំណើកែតម្រូវ',
    pendingCorrections: 'សំណើកែតម្រូវកំពុងរង់ចាំ',
    approve: 'អនុម័ត',
    reject: 'បដិសេធ',
    resolutionNote: 'កំណត់ចំណាំសម្រាប់ការសម្រេច',
    proposedChange: 'ការកែប្រែដែលបានស្នើ',
    originalValue: 'តម្លៃដើម',
    correctedValue: 'តម្លៃដែលបានកែ',
    noExceptions: 'មិនមានករណីត្រូវពិនិត្យទេ។',
    salesTitle: 'ប្រតិបត្តិការក្រុមលក់',
    salesSubtitle: 'មើលការចាប់ផ្តើមការងារ ការចុះជួបអតិថិជន ការតាមដាន និងរបាយការណ៍ថ្ងៃនេះ។',
    assigned: 'បានចាត់តាំង',
    started: 'បានចាប់ផ្តើម',
    notStarted: 'មិនទាន់ចាប់ផ្តើម',
    late: 'មកយឺត',
    visits: 'ការចុះជួប',
    uniqueOutlets: 'អតិថិជនផ្សេងគ្នា',
    submittedReports: 'របាយការណ៍បានបញ្ជូន',
    missingReports: 'របាយការណ៍ខ្វះ',
    followUps: 'ត្រូវតាមដាន',
    potentialOrders: 'ការបញ្ជាទិញសក្តានុពល',
    discountRequests: 'សំណើបញ្ចុះតម្លៃ',
    worker: 'បុគ្គលិក',
    project: 'គម្រោង',
    outlet: 'អតិថិជន / ហាង',
    result: 'លទ្ធផល',
    reportsTitle: 'របាយការណ៍វត្តមាន',
    reportsSubtitle: 'ចម្រាញ់តាមកាលបរិច្ឆេទ គម្រោង បុគ្គលិក និងករណីលើកលែង រួចនាំចេញទិន្នន័យ។',
    startDate: 'ថ្ងៃចាប់ផ្តើម',
    endDate: 'ថ្ងៃបញ្ចប់',
    exportCsv: 'នាំចេញ CSV',
    securityTitle: 'សកម្មភាពសុវត្ថិភាព',
    securitySubtitle: 'មើលការប្តូរគម្រោង ការបដិសេធសិទ្ធិ និងការភ្ជាប់ Telegram។',
    action: 'សកម្មភាព',
    target: 'គោលដៅ',
    occurredAt: 'ពេលវេលា',
    settingsTitle: 'ការកំណត់ក្រុមហ៊ុន',
    settingsSubtitle: 'កំណត់ឈ្មោះ ឡូហ្គោ ពណ៌ និងភាសាសម្រាប់ប្រព័ន្ធរបស់ក្រុមហ៊ុន។',
    companyName: 'ឈ្មោះក្រុមហ៊ុន',
    companyLogo: 'ឡូហ្គោក្រុមហ៊ុន',
    changeLogo: 'ប្តូរឡូហ្គោ',
    primaryColor: 'ពណ៌ចម្បង',
    accentColor: 'ពណ៌សម្គាល់',
    language: 'ភាសាលំនាំដើម',
    saveSettings: 'រក្សាទុកការកំណត់',
    accessScopesTitle: 'សិទ្ធិចូលប្រើគម្រោង និងការដ្ឋាន',
    accessScopesSubtitle: 'កំណត់គម្រោង និងការដ្ឋានដែលអ្នកគ្រប់គ្រង ឬអ្នកមើលអាចចូលប្រើបាន។',
    projectAccess: 'គម្រោងដែលអាចចូលប្រើ',
    siteAccess: 'ការដ្ឋានដែលអាចចូលប្រើ',
    unrestrictedAccess: 'ម្ចាស់ និងធនធានមនុស្សមានសិទ្ធិចូលប្រើទាំងអស់។',
    noAdminUsers: 'មិនមានអ្នកប្រើប្រាស់សម្រាប់កំណត់សិទ្ធិទេ។',
    saveAccess: 'រក្សាទុកសិទ្ធិ',
    localeKhmer: 'ខ្មែរ',
    localeEnglish: 'អង់គ្លេស',
    saved: 'បានរក្សាទុករួចរាល់',
    loading: 'កំពុងទាញយកទិន្នន័យ…',
    noData: 'មិនមានទិន្នន័យទេ។',
    interfaceAttendance: 'ការត្រួតពិនិត្យប្រតិបត្តិការ',
    interfaceSales: 'ប្រតិបត្តិការលក់នៅទីតាំង',
    interfaceReports: 'ការនាំចេញទិន្នន័យ',
    interfaceSecurity: 'ការគ្រប់គ្រងសិទ្ធិចូលប្រើ',
    interfaceSettings: 'អត្តសញ្ញាណប្រព័ន្ធ',
    khmerLanguage: 'ភាសាខ្មែរ',
    englishLanguage: 'ភាសាអង់គ្លេស',
    gpsEvidence: 'ភស្តុតាង GPS',
    // Outlet management
    outletManagement: 'គ្រប់គ្រងអតិថិជន / ហាង',
    outletManagementSubtitle: 'បន្ថែម កែ ឬដកហូតអតិថិជននៃគម្រោងលក់។',
    outletName: 'ឈ្មោះអតិថិជន / ហាង',
    outletCode: 'លេខកូដ (មិនបង្ខំ)',
    outletAddress: 'អាសយដ្ឋាន (មិនបង្ខំ)',
    outletActive: 'ដំណើរការ',
    outletArchived: 'បានដកហូត',
    addOutlet: 'បន្ថែមអតិថិជន',
    editOutlet: 'កែអតិថិជន',
    archiveOutlet: 'ដកហូតអតិថិជន',
    saveOutlet: 'រក្សាទុក',
    noOutlets: 'មិនទាន់មានអតិថិជនសម្រាប់គម្រោងនេះទេ។',
    // Sales report detail
    reportDetailTitle: 'លម្អិតរបាយការណ៍លក់',
    reportDate: 'ថ្ងៃរបាយការណ៍',
    reportStatus: 'ស្ថានភាព',
    reportVisits: 'ការចុះជួប',
    reportSubmittedAt: 'ពេលបញ្ជូន',
    workerStatement: 'ការពិពណ៌នារបស់បុគ្គលិក',
    visitProofPhoto: 'រូបភស្តុតាង',
    visitFollowUp: 'ត្រូវតាមដាន',
    visitPotentialOrder: 'ការបញ្ជាទិញសក្តានុពល',
    visitDiscountRequest: 'សំណើបញ្ចុះតម្លៃ',
    // Telegram health
    telegramHealthTitle: 'សុខភាព Telegram',
    telegramConnected: 'ភ្ជាប់ប្រក្រតី',
    telegramBotRemoved: 'Bot ត្រូវបានដកចេញ',
    telegramPermissionError: 'ជំហានបញ្ហាសិទ្ធិ',
    telegramPending: 'កំពុងរង់ចាំ',
    telegramLastChecked: 'ពិនិត្យចុងក្រោយ',
    telegramRefreshHealth: 'ពិនិត្យឡើងវិញ',
    // Project detail
    projectDetailTitle: 'លម្អិតគម្រោង',
    projectWorkerConnections: 'បុគ្គលិកភ្ជាប់',
    projectAttendanceHistory: 'ប្រវត្តិវត្តមាន',
    projectAccessEvents: 'ព្រឹត្តិការណ៍ចូលប្រើ',
    // Worker detail
    workerDetailTitle: 'ព័ត៌មានបុគ្គលិក',
    workerCurrentProject: 'គម្រោងបច្ចុប្បន្ន',
    workerProjectHistory: 'ប្រវត្តិគម្រោង',
    workerAttendanceHistory: 'ប្រវត្តិវត្តមាន',
    workerSecurityActivity: 'ព្រឹត្តិការណ៍សុវត្ថិភាព',
    workerPhone: 'លេខទូរស័ព្ទ',
    workerTelegramLinked: 'Telegram ភ្ជាប់',
    workerTelegramNotLinked: 'Telegram មិនទាន់ភ្ជាប់',
    connectedAt: 'ភ្ជាប់នៅ',
    lastSelected: 'ជ្រើសចុងក្រោយ',
    lastVerified: 'ផ្ទៀងផ្ទាត់ចុងក្រោយ',
    revokedAt: 'ដករហូតនៅ',
    // General
    close: 'បិទ',
    back: 'ត្រឡប់',
    edit: 'កែ',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    confirmArchive: 'ដកហូតចេញ?',
    status: 'ស្ថានភាព',
    createdAt: 'ថ្ងៃបង្កើត',
    fieldSales: 'ក្រុមលក់',
    siteBased: 'ការដ្ឋាន',
    active: 'ដំណើរការ',
    archived: 'បានដកហូត',
    draft: 'ព្រាង',
  },
  attendance: {
    open: 'បើកវត្តមាន',
    checkIn: 'ចូលវត្តមាន',
    checkOut: 'ចេញវត្តមាន',
    submit: 'បញ្ជូនវត្តមាន',
    locationRequired: 'សូមអនុញ្ញាតឱ្យប្រើទីតាំង GPS របស់អ្នក។',
    noAssignment: 'ថ្ងៃនេះអ្នកមិនមានការចាត់តាំងការងារទេ។',
    noOpenAttendance: 'មិនមានវត្តមានដែលកំពុងបើកសម្រាប់ការចេញវត្តមានទេ។ សូមចូលវត្តមានជាមុនសិន។',
    completed: 'បានបញ្ចប់វេនការថ្ងៃនេះ',
    receivingLocation: 'កំពុងទទួលទីតាំង GPS…',
    verifyingAndSubmitting: 'កំពុងផ្ទៀងផ្ទាត់ និងបញ្ជូនវត្តមាន…',
    locationUnavailable: 'មិនអាចរកទីតាំងបានទេ។ សូមបើក GPS រួចសាកល្បងម្ដងទៀត។',
    locationTimedOut: 'ការស្នើទីតាំងអស់ពេល។ សូមសាកល្បងម្ដងទៀត។',
    assignedSite: 'ការដ្ឋានដែលបានចាត់តាំង',
    allowedDistance: 'ចម្ងាយអនុញ្ញាត៖',
    todayStatus: 'ស្ថានភាពវត្តមានថ្ងៃនេះ',
    contactManager: 'សូមទាក់ទងអ្នកគ្រប់គ្រងការដ្ឋាន ឬផ្នែកធនធានមនុស្ស។',
    cameraPermission: 'សូមអនុញ្ញាតកាមេរ៉ា ដើម្បីថតរូបភស្តុតាង។',
    cameraStarting: 'កំពុងបើកកាមេរ៉ា…',
    selfieCamera: 'កាមេរ៉ាមុខ (Selfie)',
    rearCamera: 'កាមេរ៉ាក្រោយ',
    liveCameraOnly: 'ថតផ្ទាល់ពីកាមេរ៉ាប៉ុណ្ណោះ។ មិនមានការជ្រើសរូបពី Gallery ទេ។',
    cameraDenied: 'កាមេរ៉ាត្រូវបានបដិសេធ។ សូមអនុញ្ញាតកាមេរ៉ាសម្រាប់ Telegram និងគេហទំព័រនេះ រួចសាកល្បងម្ដងទៀត។',
    cameraUnsupported: 'Telegram នេះមិនអាចបើកកាមេរ៉ាផ្ទាល់បានទេ។ សូមធ្វើបច្ចុប្បន្នភាព Telegram រួចបើក Mini App ម្ដងទៀត។',
    cameraInsecure: 'ត្រូវបើក Mini App តាមតំណ HTTPS ដើម្បីប្រើកាមេរ៉ា។',
    cameraBusy: 'មិនអាចប្រើកាមេរ៉ាបានទេ។ សូមបិទកម្មវិធីផ្សេងដែលកំពុងប្រើកាមេរ៉ា រួចសាកល្បងម្ដងទៀត។',
    cameraTimedOut: 'កាមេរ៉ាមិនទាន់ឆ្លើយតប។ សូមពិនិត្យសិទ្ធិកាមេរ៉ា រួចចុចសាកល្បងម្ដងទៀត។',
    cameraUnavailable: 'មិនអាចបើកកាមេរ៉ាបានទេ។ សូមសាកល្បងកាមេរ៉ាមុខ ឬកាមេរ៉ាក្រោយម្ដងទៀត។',
    cameraRetry: 'សាកល្បងកាមេរ៉ាម្ដងទៀត',
    cameraFallback: 'បើកកាមេរ៉ាទូរស័ព្ទ',
    cameraFallbackHint: 'បើកាមេរ៉ាមិនបង្ហាញ សូមប្រើប៊ូតុងនេះដើម្បីថតរូប។',
    invalidPhoto: 'មិនអាចប្រើរូបនេះបានទេ។ សូមថតម្ដងទៀត។',
    proofPhotoTitle: 'ថតរូបភស្តុតាង',
    proofPhotoHint: 'សូមបង្ហាញមុខ និងការដ្ឋានឱ្យច្បាស់',
    proofPhotoAlt: 'រូបភស្តុតាង',
    close: 'បិទ',
    retakePhoto: 'ថតម្ដងទៀត',
    takePhoto: 'ថតរូប',
    checkInWithPhoto: 'ចូលការជាមួយរូប',
    recordVisit: 'កត់ត្រាការចុះជួប',
    recordVisitWithPhoto: 'បញ្ជូនការចុះជួប',
    visitCustomer: 'ឈ្មោះអតិថិជន (មិនបង្ខំ)',
    visitNote: 'កំណត់ចំណាំ (មិនបង្ខំ)',
    currentProject: 'គម្រោងបច្ចុប្បន្ន',
    changeProject: 'ប្តូរគម្រោង',
    chooseProject: 'ជ្រើសគម្រោងសម្រាប់ការចូលវត្តមាន',
    chooseProjectHint: 'ជ្រើសតែគម្រោងដែលអ្នកបានភ្ជាប់តាមក្រុម Telegram។',
    noConnectedProjects: 'អ្នកមិនទាន់បានភ្ជាប់គម្រោងណាមួយទេ។ សូមចូលក្រុម Telegram របស់គម្រោង ហើយចុច «កំណត់ជាគម្រោងបច្ចុប្បន្ន»។',
    noCurrentProject: 'អ្នកមិនទាន់មានគម្រោងបច្ចុប្បន្នទេ។ សូមបើកក្រុម Telegram របស់គម្រោង ហើយចុច «កំណត់ជាគម្រោងបច្ចុប្បន្ន»។',
    registrationPending: 'គណនីរបស់អ្នកកំពុងរង់ចាំការអនុម័តពីអ្នកគ្រប់គ្រង។',
    telegramUnlinked: 'គណនី Telegram របស់អ្នកមិនទាន់ភ្ជាប់ជាមួយបុគ្គលិកទេ។ សូមផ្ញើ /start ឬចែករំលែកលេខទូរស័ព្ទក្នុង bot។',
    authenticationFailed: 'មិនអាចផ្ទៀងផ្ទាត់ការចូលប្រើបានទេ។',
    scheduleLoadFailed: 'មិនអាចទាញយកវេនការបានទេ។',
    geolocationUnsupported: 'ទូរស័ព្ទរបស់អ្នកមិនគាំទ្រការទាញយកទីតាំងទេ។',
    requestFailed: 'មិនអាចបញ្ជូនសំណើវត្តមានបានទេ។ សូមសាកល្បងម្ដងទៀត។',
    submissionUnconfirmed: 'កំពុងពិនិត្យលទ្ធផលនៃសំណើរបស់អ្នក។ សំណើអាចបានរក្សាទុករួចហើយ។ សូមពិនិត្យស្ថានភាពវត្តមានមុនពេលសាកល្បងម្ដងទៀត។',
    locationAccessFailed: 'មិនអាចប្រើទីតាំងបានទេ។',
    unassignedPosition: 'មិនទាន់កំណត់តួនាទី',
    telegramRequired: 'សូមបើកកម្មវិធីនេះពីក្នុង Telegram។',
    telegramRequiredHint: 'កម្មវិធីនេះត្រូវបានរៀបចំសម្រាប់ប្រើក្នុង Telegram bot។',
    checkApiStatus: 'ពិនិត្យស្ថានភាពម៉ាស៊ីនមេ',
    apiOffline: 'ម៉ាស៊ីនមេមិនដំណើរការ។',
    browserTestHint: 'សម្រាប់សាកល្បង សូមបើកកម្មវិធីនេះក្នុង Telegram bot។',
    shiftSchedule: 'វេនការ',
    timezone: 'តំបន់ពេលវេលា',
    checkInSuccess: 'បានចូលវត្តមានរួចរាល់',
    checkOutSuccess: 'បានចេញវត្តមានរួចរាល់',
    visitSuccess: 'បានកត់ត្រាការចុះជួបរួចរាល់',
    recordedWithWarning: 'បានកត់ត្រា ប៉ុន្តែទីតាំងត្រូវការការពិនិត្យ',
    distanceFromSite: (distance: number) => `ចម្ងាយពីការដ្ឋាន៖ ${distance} ម៉ែត្រ`,
    siteMode: 'ការងារតាមការដ្ឋាន',
    salesMode: 'ការងារក្រុមលក់',
    startWork: 'ចាប់ផ្តើមការងារ',
    endWork: 'បញ្ចប់ការងារ',
    selectOutlet: 'ជ្រើសអតិថិជន ឬហាង',
    otherCustomer: 'អតិថិជនក្រៅបញ្ជី',
    salesVisitHint: 'ថតរូបនៅទីតាំងអតិថិជន ដើម្បីកត់ត្រាការចុះជួប។',
    todayVisits: 'ការចុះជួបថ្ងៃនេះ',
    noVisitsYet: 'មិនទាន់មានការចុះជួបនៅថ្ងៃនេះទេ។',
    dailyReport: 'របាយការណ៍ប្រចាំថ្ងៃ',
    reportDraft: 'កំពុងរៀបចំ',
    reportSubmitted: 'បានបញ្ជូន',
    completeVisitContext: 'បំពេញលទ្ធផលការចុះជួប',
    visitResult: 'លទ្ធផលនៃការចុះជួប',
    followUpRequired: 'ត្រូវតាមដានបន្ត',
    followUpAt: 'កាលបរិច្ឆេទត្រូវតាមដាន',
    potentialOrderQuantity: 'ចំនួនបញ្ជាទិញសក្តានុពល (មិនបង្ខំ)',
    requestedDiscountPerItem: 'សំណើបញ្ចុះតម្លៃក្នុងមួយឯកតា (មិនបង្ខំ)',
    workerStatement: 'ការពិពណ៌នារបស់អ្នក',
    saveVisitResult: 'រក្សាទុកលទ្ធផល',
    reportSummary: 'សេចក្តីសង្ខេបប្រចាំថ្ងៃ',
    additionalNote: 'កំណត់ចំណាំបន្ថែម',
    saveReport: 'រក្សាទុករបាយការណ៍',
    submitReport: 'បញ្ជូនរបាយការណ៍',
    reportRequiresCheckout: 'សូមបញ្ចប់ការងារមុនពេលបញ្ជូនរបាយការណ៍។',
    reportRequiresVisitDetails: 'សូមបំពេញលទ្ធផលការចុះជួបទាំងអស់ជាមុនសិន។',
  },
  schedules: {
    editTitle: 'កែប្រែវេនការ៖ {name}',
    editSubtitle: 'កែប្រែម៉ោងចូល ម៉ោងចេញ រយៈពេលអនុគ្រោះ និងតំបន់ពេលវេលា។',
    name: 'ឈ្មោះវេនការ *',
    startTime: 'ម៉ោងចូល *',
    endTime: 'ម៉ោងចេញ *',
    gracePeriod: 'រយៈពេលអនុគ្រោះ (នាទី)',
    timezone: 'តំបន់ពេលវេលា *',
    saving: 'កំពុងរក្សាទុក…',
    saveChanges: 'រក្សាទុកការកែប្រែ',
    cancel: 'បោះបង់',
  },
  sites: {
    mapHint: 'ចុចលើផែនទី ឬអូសម្ជុលក្រហមទៅច្រកចូលការដ្ឋាន។',
  },
  telegram: {
    mainMenuGreeting: (name: string) => `សួស្តី ${name}! សូមជ្រើសមុខងារខាងក្រោម ដើម្បីកត់ត្រាវត្តមាន ឬពិនិត្យស្ថានភាព។`,
    verifyOwnContact: 'ការផ្ទៀងផ្ទាត់បរាជ័យ។ សូមចុចប៊ូតុងដើម្បីចែករំលែកលេខទូរស័ព្ទផ្ទាល់ខ្លួន មិនមែនបញ្ជូនកាតទំនាក់ទំនងទេ។',
    invalidPhone: 'លេខទូរស័ព្ទមិនត្រឹមត្រូវ។ សូមសាកល្បងម្ដងទៀត។',
    alreadyRegistered: (name: string, code: string, organization: string) => `គណនីរបស់អ្នកបានចុះឈ្មោះរួចហើយ។\n\nសូមស្វាគមន៍ ${name} (${code})។ គណនីនេះស្ថិតក្រោម ${organization}។\n\nសូមបើកកម្មវិធីវត្តមានដើម្បីចូលការ។`,
    registrationSuccess: (name: string, code: string, organization: string) => `បានផ្ទៀងផ្ទាត់លេខទូរស័ព្ទរួចរាល់។\n\nសូមស្វាគមន៍ ${name}\n• លេខសម្គាល់បុគ្គលិក៖ ${code}\n• អង្គភាព៖ ${organization}\n\nអ្នកអាចបើកកម្មវិធីវត្តមានដើម្បីកត់ត្រាការងារ។`,
    unlinkedWelcome: (name: string) => `សួស្តី ${name}!\n\nសូមស្វាគមន៍មកកាន់ប្រព័ន្ធវត្តមាន។\n\nសូមចុចប៊ូតុងខាងក្រោម ដើម្បីចែករំលែកលេខទូរស័ព្ទផ្ទាល់ខ្លួនសម្រាប់ផ្ទៀងផ្ទាត់គណនី។`,
    sharePhone: 'ចែករំលែកលេខទូរស័ព្ទដើម្បីចុះឈ្មោះ',
    startWelcome: (name: string, code: string, organization: string) => `សូមស្វាគមន៍ ${name}!\n• លេខសម្គាល់បុគ្គលិក៖ ${code}\n• អង្គភាព៖ ${organization}\n\nសូមចុច «បើកកម្មវិធីវត្តមាន» ដើម្បីកត់ត្រាការងារ។`,
    checkInPrompt: (name: string) => `បើកកម្មវិធីវត្តមានដើម្បីចូលការ\nបុគ្គលិក៖ ${name}\n\nកម្មវិធីនឹងថតរូបភស្តុតាង និងទាញយក GPS នៅពេលអ្នកបញ្ជូន។`,
    checkOutPrompt: (name: string) => `បើកកម្មវិធីវត្តមានដើម្បីចេញការ\nបុគ្គលិក៖ ${name}\n\nកម្មវិធីនឹងទាញយក GPS និងបង្ហាញលទ្ធផលដែលបានបញ្ជាក់។`,
    openAttendance: 'បើកកម្មវិធីវត្តមាន',
    todayStatusButton: 'ស្ថានភាពថ្ងៃនេះ',
    helpButton: 'ជំនួយ',
    noAssignmentToday: 'អ្នកមិនមានវេនការសកម្មសម្រាប់ថ្ងៃនេះទេ។ សូមទាក់ទងអ្នកគ្រប់គ្រង ប្រសិនបើអ្នកត្រូវធ្វើការថ្ងៃនេះ។',
    statusLoadFailed: 'មិនអាចទាញយកស្ថានភាពបានទេ។ សូមសាកល្បងម្ដងទៀត។',
    shiftReminder: (site: string, startTime: string) => `វេនការរបស់អ្នកនៅ ${site} នឹងចាប់ផ្តើមនៅម៉ោង ${startTime}។ សូមបើកកម្មវិធីវត្តមានដើម្បីចូលការនៅពេលមកដល់។`,
    missingCheckoutNotice: (site: string, endTime: string) => `វេនការរបស់អ្នកនៅ ${site} បានបញ្ចប់នៅម៉ោង ${endTime} ប៉ុន្តែមិនមានការចេញការទេ។ សូមទាក់ទងអ្នកគ្រប់គ្រងការដ្ឋាន។`,
    helpText: 'ជំនួយប្រព័ន្ធវត្តមាន\n\n• ចុះឈ្មោះ៖ ចែករំលែកលេខទូរស័ព្ទផ្ទាល់ខ្លួនដើម្បីផ្ទៀងផ្ទាត់។\n• ចូលការ៖ បើកកម្មវិធីវត្តមាន ហើយបញ្ជូនរូបថត និង GPS។\n• ចេញការ៖ បើកកម្មវិធីវត្តមាន ហើយបញ្ជូន GPS។\n• ស្ថានភាព៖ ផ្ញើ /status ដើម្បីមើលវេនការ និងពេលវេលា។\n\nអ្នកត្រូវស្ថិតនៅក្នុងរង្វង់ទីតាំងដែលបានកំណត់។ ម៉ាស៊ីនមេជាអ្នកផ្ទៀងផ្ទាត់ទីតាំង និងពេលវេលាផ្លូវការ។',
    attendanceStatusSummary: (date: string, timezone: string, name: string, code: string, site: string, schedule: string, status: string, checkIn: string, checkOut: string, duration: string) => `ស្ថានភាពវត្តមានថ្ងៃនេះ\nកាលបរិច្ឆេទ៖ ${date} (${timezone})\n\nបុគ្គលិក៖ ${name} (${code})\nការដ្ឋាន៖ ${site}\nវេនការ៖ ${schedule}\n\n• ស្ថានភាព៖ ${status}\n• ចូលការ៖ ${checkIn}\n• ចេញការ៖ ${checkOut}${duration ? `\n• រយៈពេល៖ ${duration}` : ''}`,
    pendingValue: 'មិនទាន់មាន',
    durationHoursMinutes: (hours: number, minutes: number) => `${hours} ម៉ោង ${minutes} នាទី`,
    groupConnected: 'ក្រុមនេះត្រូវបានភ្ជាប់រួចរាល់។ សូមឱ្យអ្នកគ្រប់គ្រងកំណត់ក្រុមនេះទៅការដ្ឋាន ឬក្រុមការងារ មុនពេលបើកការជូនដំណឹង។',
    ownerPairingRequired: (url: string) => `សូមឱ្យម្ចាស់អង្គភាពបើក [bot ផ្ទាល់ខ្លួន](${url}) ដើម្បីភ្ជាប់ Telegram ជាមុនសិន។`,
    ownerPairingComplete: 'បានភ្ជាប់ Telegram ជាមួយអង្គភាពរួចរាល់។ ឥឡូវនេះ អ្នកអាចត្រឡប់ទៅក្រុម ហើយផ្ញើ /connect។',
    ownerPairingStart: 'ភ្ជាប់ម្ចាស់ Telegram',
    ownerPairingHint: 'បង្កើតតំណភ្ជាប់ម្តងតែមួយ ហើយបើកវានៅក្នុង Telegram របស់ម្ចាស់អង្គភាព។',
    joinProject: (name: string) => `ចូលរួម ${name}`,
    projectJoinReady: (name: string) => `គម្រោង ${name} រួចរាល់។ សូមចុចប៊ូតុងខាងក្រោម ដើម្បីចុះឈ្មោះសម្រាប់គម្រោងនេះ។`,
    groupAlreadyConnected: 'ក្រុមនេះត្រូវបានភ្ជាប់រួចហើយ ហើយកំពុងរង់ចាំការកំណត់ដោយអ្នកគ្រប់គ្រង។',
    groupBelongsToAnotherOrganization: 'ក្រុមនេះត្រូវបានភ្ជាប់ទៅអង្គភាពផ្សេងរួចហើយ។',
    projectConnected: 'គម្រោងនេះត្រូវបានភ្ជាប់ជាមួយប្រព័ន្ធវត្តមានរួចរាល់។',
    setCurrentProject: 'កំណត់ជាគម្រោងបច្ចុប្បន្ន',
    currentProjectUpdated: 'បានកំណត់គម្រោងបច្ចុប្បន្នរួចរាល់។ ការចូលវត្តមានលើកបន្ទាប់នឹងកត់ត្រាទៅគម្រោងនេះ។',
    projectUnavailable: 'មិនអាចភ្ជាប់ទៅគម្រោងនេះបានទេ។ សូមទាក់ទងអ្នកគ្រប់គ្រងគម្រោង។',
    registrationRequired: (url: string) => `ដើម្បីប្រើគម្រោងនេះ សូមបើក [bot ផ្ទាល់ខ្លួន](${url}) រួចចែករំលែកលេខទូរស័ព្ទរបស់អ្នក។ បន្ទាប់ពីបានអនុម័ត គម្រោងនេះនឹងក្លាយជាគម្រោងបច្ចុប្បន្ន។`,
    registrationPending: 'សំណើចុះឈ្មោះរបស់អ្នកត្រូវបានផ្ញើទៅអ្នកគ្រប់គ្រងរួចហើយ។ បន្ទាប់ពីបានអនុម័ត គម្រោងដែលអ្នកបានជ្រើសនឹងក្លាយជាគម្រោងបច្ចុប្បន្ន។',
    registrationNeedsProject: 'មិនទាន់អាចផ្ញើសំណើចុះឈ្មោះបានទេ។ សូមចូលក្រុម Telegram របស់គម្រោង ផ្ញើ /connect ហើយចុច «កំណត់ជាគម្រោងបច្ចុប្បន្ន» ជាមុនសិន។',
    reportingTitle: 'កំណត់ក្រុម Telegram',
    reportingDescription: 'ភ្ជាប់ក្រុម Telegram ទៅការដ្ឋាន ឬក្រុមការងារ។ ការជូនដំណឹងបើកបានតែក្រោយពេលកំណត់ទិសដៅ។',
    reportingActive: 'បានបើកការជូនដំណឹង',
    reportingPending: 'កំពុងរង់ចាំការកំណត់',
    reportingDestination: 'ទិសដៅសារ',
    reportingNone: 'មិនទាន់កំណត់ / បិទ',
    reportingSites: 'ការដ្ឋាន',
    reportingWorkerGroups: 'ក្រុមការងារ',
    reportingEmpty: 'មិនទាន់មានក្រុមភ្ជាប់ទេ។ បន្ថែម bot ទៅក្រុម រួចផ្ញើ /connect។',
    checkInCaption: (
      workerName: string,
      projectName: string,
      time: string,
      options?: {
        isOutside?: boolean;
        isLate?: boolean;
        distanceMeters?: number | null;
        accuracyMeters?: number | null;
      },
    ) => {
      const locationRemark = options?.isOutside
        ? `⚠️ ទីតាំង៖ ខាងក្រៅការដ្ឋាន${options.distanceMeters != null ? ` (ចម្ងាយ ~${Math.round(options.distanceMeters)}m)` : ''}`
        : '📍 ទីតាំង៖ ក្នុងបរិវេណការដ្ឋាន (បានផ្ទៀងផ្ទាត់)';
      const statusRemark = options?.isOutside
        ? '⚠️ ស្ថានភាព៖ ខាងក្រៅការដ្ឋាន'
        : options?.isLate
        ? '⚠️ ស្ថានភាព៖ ចូលយឺត (Late)'
        : '✅ ស្ថានភាព៖ ចូលទាន់ពេល (On Time)';

      return `📋 កំណត់ត្រាវត្តមានចូលការ (Check-In)\n\n👷 បុគ្គលិក៖ ${workerName}\n🏗 គម្រោង/ការដ្ឋាន៖ ${projectName}\n⏰ ម៉ោងចូល៖ ${time}\n${locationRemark}\n${statusRemark}`;
    },
    checkOutCaption: (
      workerName: string,
      projectName: string,
      checkIn: string,
      checkOut: string,
      duration: string,
      options?: {
        isOutside?: boolean;
      },
    ) => {
      const locationRemark = options?.isOutside
        ? '⚠️ ទីតាំង៖ ខាងក្រៅការដ្ឋាន'
        : '📍 ទីតាំង៖ ក្នុងបរិវេណការដ្ឋាន (បានផ្ទៀងផ្ទាត់)';

      return `📋 កំណត់ត្រាវត្តមានចេញការ (Check-Out)\n\n👷 បុគ្គលិក៖ ${workerName}\n🏗 គម្រោង/ការដ្ឋាន៖ ${projectName}\n🕐 ម៉ោងចូល៖ ${checkIn}\n🕔 ម៉ោងចេញ៖ ${checkOut}\n⏱ រយៈពេលបំពេញការងារ៖ ${duration}\n${locationRemark}\n✅ ស្ថានភាព៖ បានបញ្ចប់វេនការងារ`;
    },
    salesReportReady: 'ការងារថ្ងៃនេះបានបញ្ចប់។ របាយការណ៍លក់ប្រចាំថ្ងៃរបស់អ្នកបានត្រៀមរួច ហើយត្រូវការព័ត៌មានអាជីវកម្មដែលនៅខ្វះ។',
    openSalesReport: 'បំពេញរបាយការណ៍ថ្ងៃនេះ',
    salesReportComplete: 'ព័ត៌មានការចុះជួបទាំងអស់បានបំពេញរួច។ អ្នកអាចបន្ថែមកំណត់ចំណាំ ឬបញ្ជូនរបាយការណ៍។',
    salesReportVisitPrompt: (index: number, name: string) => `ការចុះជួបទី ${index} — ${name}\nតើលទ្ធផលនៃការចុះជួបនេះយ៉ាងដូចម្តេច?`,
    salesReportNotePrompt: 'សូមផ្ញើកំណត់ចំណាំបន្ថែមសម្រាប់របាយការណ៍ថ្ងៃនេះ។',
    salesReportSubmitted: 'របាយការណ៍លក់ប្រចាំថ្ងៃត្រូវបានបញ្ជូនរួចរាល់។',
    salesReportNotAvailable: 'មិនទាន់មានរបាយការណ៍លក់សម្រាប់ថ្ងៃនេះទេ។ សូមចាប់ផ្តើម និងបញ្ចប់ការងារជាមុនសិន។',
    unknownOutlet: 'អតិថិជនមិនទាន់មានឈ្មោះ',
    addReportNote: 'បន្ថែមកំណត់ចំណាំ',
    submitSalesReport: 'បញ្ជូនរបាយការណ៍',
    ownerRegistrationNotification: (name: string, phone: string, username: string | null) =>
      `📋 *សំណើចុះឈ្មោះថ្មី*\n\n👤 ឈ្មោះ៖ ${name}\n📞 ទូរស័ព្ទ៖ ${phone}${username ? `\n🔗 Telegram៖ @${username}` : ''}\n\nសូមចុចប៊ូតុងខាងក្រោមដើម្បីអនុម័ត ឬបដិសេធ។`,
    approveRegistration: '✅ អនុម័ត',
    rejectRegistration: '❌ បដិសេធ',
    registrationApprovedByOwner: (name: string) => `✅ បានអនុម័តសំណើចុះឈ្មោះរបស់ ${name} រួចរាល់។`,
    registrationRejectedByOwner: (name: string) => `❌ បានបដិសេធសំណើចុះឈ្មោះរបស់ ${name}។`,
    registrationAlreadyResolved: 'សំណើចុះឈ្មោះនេះត្រូវបានដោះស្រាយរួចហើយ។',
  },
  status: {
    NOT_STARTED: 'មិនទាន់ចូលវត្តមាន',
    ON_TIME: 'ចូលទាន់ពេល',
    LATE: 'ចូលយឺត',
    COMPLETED: 'បានបញ្ចប់',
    EARLY_CHECKOUT: 'ចេញមុនពេល',
    MISSING_CHECKOUT: 'ខកខានចេញវត្តមាន',
    OUTSIDE_GEOFENCE: 'ខាងក្រៅការដ្ឋាន',
    LOW_ACCURACY: 'GPS មិនច្បាស់លាស់',
    PENDING_REVIEW: 'កំពុងរង់ចាំពិនិត្យ',
  },
  operations: {
    employeeAndSite: 'បុគ្គលិក និងការដ្ឋាន',
    checkIn: 'ចូលការ',
    checkOut: 'ចេញការ',
    status: 'ស្ថានភាព',
    details: 'លម្អិត',
  },
} as const;
