'use client';

import { Calendar, Plus, Trash2 } from 'lucide-react';
import type { AssignmentListItem, EmployeeListItem, ProjectListItem, SiteListItem, WorkScheduleListItem } from '@workforce/contracts';

export function AssignmentTable({ assignments, employees, sites, schedules, projects, title, subtitle, addLabel, onAdd, onDelete }: {
  assignments: AssignmentListItem[]; employees: EmployeeListItem[]; sites: SiteListItem[]; schedules: WorkScheduleListItem[]; projects: ProjectListItem[];
  title: string; subtitle: string; addLabel: string; onAdd: () => void; onDelete: (id: string) => void;
}) {
  return <div className="space-y-4"><div className="flex flex-col justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-xs md:flex-row md:items-center"><div><h2 className="text-base font-extrabold text-slate-900">{title}</h2><p className="mt-0.5 text-xs text-slate-500">{subtitle}</p></div><button type="button" onClick={onAdd} className="inline-flex shrink-0 cursor-pointer items-center space-x-1.5 rounded-xl bg-[var(--portal-primary)] px-4 py-2 text-xs font-bold text-white shadow-xs transition-all hover:brightness-90"><Plus size={14} /><span>{addLabel}</span></button></div>
    {assignments.length === 0 ? <div className="rounded-2xl border border-slate-200 bg-white py-12 text-center text-xs text-slate-500"><Calendar className="mx-auto mb-2 size-8 text-slate-300" />មិនទាន់មានការចាត់តាំងបុគ្គលិកនៅឡើយទេ។</div> : <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs"><table className="w-full text-left text-xs"><thead className="border-b border-slate-200 bg-slate-50 text-[10px] font-bold uppercase text-slate-500"><tr><th className="px-5 py-3.5">បុគ្គលិក (Worker)</th><th className="px-4 py-3.5">ការដ្ឋាន & គម្រោង (Site & Project)</th><th className="px-4 py-3.5">វេនការ & អនុគ្រោះយឺត (Schedule & Grace)</th><th className="px-4 py-3.5">កាលបរិច្ឆេទ (Valid Dates)</th><th className="px-4 py-3.5 text-right">សកម្មភាព (Actions)</th></tr></thead><tbody className="divide-y divide-slate-100 text-slate-700">{assignments.map((assignment) => { const employee = employees.find((item) => item.id === assignment.employeeId); const site = sites.find((item) => item.id === assignment.siteId); const schedule = schedules.find((item) => item.id === assignment.scheduleId); const project = projects.find((item) => item.id === site?.projectId); return <tr key={assignment.id} className="transition-colors hover:bg-slate-50/80"><td className="px-5 py-3.5"><div className="font-extrabold text-slate-900">{employee?.fullName || assignment.employeeId}</div><div className="font-mono text-[10px] text-slate-400">{employee?.employeeCode}</div></td><td className="px-4 py-3.5"><div className="font-bold text-slate-800">{site?.name || 'Site'}</div><div className="text-[10px] text-slate-400">{project?.name || 'Project'}</div></td><td className="px-4 py-3.5"><div className="font-bold text-slate-800">{schedule?.name || 'Schedule'}</div><div className="text-[10px] font-semibold text-amber-700">{schedule?.startTime} - {schedule?.endTime} (+{schedule?.graceMinutes ?? 0}mn grace)</div></td><td className="px-4 py-3.5 font-mono text-[11px] text-slate-600">{assignment.startsOn} → {assignment.endsOn || 'Ongoing'}</td><td className="px-4 py-3.5 text-right"><button type="button" onClick={() => onDelete(assignment.id)} className="cursor-pointer rounded-xl p-1.5 text-slate-400 transition-colors hover:bg-rose-50 hover:text-rose-600" title="Remove Assignment"><Trash2 size={13} /></button></td></tr>; })}</tbody></table></div>}
  </div>;
}
